"""Build the docs index for {{APP_TITLE}}.

Walks ``docs/`` recursively and produces:

- ``docs/INDEX.md``    — human-readable table of contents
- ``docs/_index.json`` — machine-readable manifest for embedding pipelines

See ``docs/docs-pattern/03_topic_docs.md`` for the pattern.

Usage:

    python3 scaffold/python/build_docs_index.py            # from project root
    python3 scaffold/python/build_docs_index.py --docs docs
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import asdict, dataclass, field
from datetime import date
from pathlib import Path
from typing import List, Tuple

HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$", re.MULTILINE)
FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")


@dataclass
class DocEntry:
    path: str
    title: str
    status: str
    headings: List[Tuple[int, str]]
    lines: int
    links: List[str] = field(default_factory=list)


def parse_frontmatter(text: str) -> dict:
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}
    out: dict = {}
    for line in match.group(1).splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        out[key.strip()] = value.strip().strip('"').strip("'")
    return out


def parse_doc(path: Path) -> DocEntry:
    text = path.read_text(encoding="utf-8", errors="replace")
    fm = parse_frontmatter(text)
    headings = [(len(m.group(1)), m.group(2)) for m in HEADING_RE.finditer(text)]
    # Title: frontmatter first, else first H1, else filename.
    title = fm.get("title") or next(
        (h[1] for h in headings if h[0] == 1), path.stem
    )
    links = [m.group(2) for m in LINK_RE.finditer(text)]
    return DocEntry(
        path=str(path),
        title=title,
        status=fm.get("status", "unknown"),
        headings=headings,
        lines=len(text.splitlines()),
        links=links,
    )


def build(docs_dir: Path) -> List[DocEntry]:
    entries: List[DocEntry] = []
    for md in sorted(docs_dir.rglob("*.md")):
        if md.name in {"INDEX.md", "_index.json"}:
            continue
        entries.append(parse_doc(md))
    return entries


def write_json_index(entries: List[DocEntry], out_path: Path) -> None:
    payload = {
        "generated": date.today().isoformat(),
        "doc_count": len(entries),
        "docs": [asdict(e) for e in entries],
    }
    out_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def write_md_index(entries: List[DocEntry], out_path: Path, docs_dir: Path) -> None:
    lines = [
        "---",
        "title: \"Docs Index\"",
        "status: generated",
        f"generated: {date.today().isoformat()}",
        "---",
        "",
        "# Docs Index",
        "",
        f"> Auto-generated by `build_docs_index.py`. Do not hand-edit.",
        f"> {len(entries)} docs indexed.",
        "",
    ]
    by_dir: dict[str, list[DocEntry]] = {}
    for e in entries:
        rel = Path(e.path).relative_to(docs_dir)
        bucket = str(rel.parent) if rel.parent != Path(".") else "(root)"
        by_dir.setdefault(bucket, []).append(e)
    for bucket in sorted(by_dir.keys()):
        lines.append(f"## `{bucket}/`" if bucket != "(root)" else "## Top level")
        lines.append("")
        lines.append("| Title | Status | Lines | Path |")
        lines.append("|---|---|---|---|")
        for e in sorted(by_dir[bucket], key=lambda x: x.title.lower()):
            rel = Path(e.path).relative_to(docs_dir)
            lines.append(f"| {e.title} | {e.status} | {e.lines} | `{rel}` |")
        lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the docs index.")
    parser.add_argument("--docs", default="docs",
                        help="Path to the docs directory (default: ./docs).")
    args = parser.parse_args(argv)

    docs_dir = Path(args.docs).resolve()
    if not docs_dir.is_dir():
        print(f"error: {docs_dir} is not a directory", file=sys.stderr)
        return 2

    entries = build(docs_dir)
    write_json_index(entries, docs_dir / "_index.json")
    write_md_index(entries, docs_dir / "INDEX.md", docs_dir)
    print(f"build_docs_index: indexed {len(entries)} docs in {docs_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
