"""Tests for truth/state drift detection and Codex startup output."""

from __future__ import annotations

import argparse
import io
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path
from unittest.mock import patch

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from cli.doctor import (  # noqa: E402
    check_handoff_numbering,
    check_start_handoff_conflict,
    check_test_count_drift,
    check_version_drift,
)
from cli.orient import run_orient  # noqa: E402
from cli.start_codex import render_codex_prompt, run_codex, run_start_codex  # noqa: E402
from context_kit import build_parser  # noqa: E402


def _write_min_project(project: Path, *, version: str = "0.15.0") -> None:
    (project / "docs" / "handoffs").mkdir(parents=True)
    (project / "tests").mkdir()
    (project / "pyproject.toml").write_text(
        f'[project]\nname = "demo"\nversion = "{version}"\n',
        encoding="utf-8",
    )
    (project / "00-START-NEXT-SESSION.md").write_text(
        f"""# Next Session

## Current State

- Version: `{version}`
- Latest handoff: `SESSION_001`

## Next Task

Implement the next thing.
""",
        encoding="utf-8",
    )
    (project / "docs" / "handoffs" / "SESSION_001_BOOTSTRAP.md").write_text(
        f"""# Session 001

Version {version}.

## Recommended next work

Implement the next thing.
""",
        encoding="utf-8",
    )
    sample_test = "import unittest\n\n" + """class TestSample(unittest.TestCase):
    def """ + """test_one(self):
        self.assertTrue(True)
"""
    (project / "tests" / "test_sample.py").write_text(
        sample_test,
        encoding="utf-8",
    )
    _write_inventory_count(project, 1)


def _write_inventory_count(project: Path, count: int) -> None:
    inventory = project / "docs" / "CONTEXT_KIT_INVENTORY.md"
    inventory.write_text(
        f"""# Inventory

<!-- context-kit:inventory:start -->
<!-- Auto-generated by `context-kit inventory --write`. Do not edit by hand. -->
<!-- Last generated: 2026-05-02T00:00:00+00:00 -->
<!-- Schema version: 1 -->

## Auto-generated counts

| Item | Count | Notes |
|---|---|---|
| Tests collected | {count} | from `def test_` parse |
<!-- context-kit:inventory:end -->
""",
        encoding="utf-8",
    )


class TruthStateTestCase(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.project = Path(self._tmp.name) / "demo"
        self.project.mkdir()
        _write_min_project(self.project)

    def tearDown(self):
        self._tmp.cleanup()


class TestVersionDrift(TruthStateTestCase):
    def test_ok_when_docs_match_pyproject(self):
        result = check_version_drift(self.project)
        self.assertEqual(result.status, "ok")

    def test_warns_when_start_or_handoff_mentions_different_version(self):
        (self.project / "00-START-NEXT-SESSION.md").write_text(
            "# Next\n\nVersion: 0.14.0\nLatest handoff: SESSION_001\n",
            encoding="utf-8",
        )
        result = check_version_drift(self.project)
        self.assertEqual(result.status, "warning")
        self.assertIn("0.15.0", result.detail)
        self.assertIn("0.14.0", result.detail)


class TestTestCountDrift(TruthStateTestCase):
    def test_warns_when_unittest_count_differs_from_inventory(self):
        _write_inventory_count(self.project, 99)
        result = check_test_count_drift(self.project)
        self.assertEqual(result.status, "warning")
        self.assertIn("1", result.detail)
        self.assertIn("99", result.detail)


class TestHandoffContinuity(TruthStateTestCase):
    def test_warns_when_numbered_handoff_gap_exists(self):
        (self.project / "docs" / "handoffs" / "SESSION_003_GAP.md").write_text(
            "# Session 003\n", encoding="utf-8"
        )
        result = check_handoff_numbering(self.project)
        self.assertEqual(result.status, "warning")
        self.assertIn("SESSION_002", result.detail)

    def test_warns_when_start_points_at_different_session(self):
        (self.project / "00-START-NEXT-SESSION.md").write_text(
            "# Next\n\nLatest handoff: SESSION_002\n\n## Next Task\n\nImplement the next thing.\n",
            encoding="utf-8",
        )
        result = check_start_handoff_conflict(self.project)
        self.assertEqual(result.status, "warning")
        self.assertIn("SESSION_002", result.detail)
        self.assertIn("SESSION_001", result.detail)
        self.assertIn("Verify", " ".join(result.fix or []))

    def test_start_task_mismatch_is_worded_as_verification_needed(self):
        (self.project / "00-START-NEXT-SESSION.md").write_text(
            "# Next\n\nLatest handoff: SESSION_001\n\n## Next Task\n\nDo different work.\n",
            encoding="utf-8",
        )
        result = check_start_handoff_conflict(self.project)
        self.assertEqual(result.status, "warning")
        self.assertIn("Verify", result.detail)
        self.assertIn("found verbatim", result.detail)
        self.assertIn("intentionally supersedes", " ".join(result.fix or []))


class TestOrientRuntimeState(TruthStateTestCase):
    def test_full_orient_includes_runtime_state_block(self):
        buf = io.StringIO()
        with redirect_stdout(buf):
            rc = run_orient(argparse.Namespace(command="orient", project=str(self.project), short=False))
        self.assertEqual(rc, 0)
        out = buf.getvalue()
        self.assertIn("## CURRENT RUNTIME STATE", out)
        self.assertIn("Version: 0.15.0", out)
        self.assertIn("Latest handoff: SESSION_001", out)

    def test_short_orient_includes_runtime_state_block(self):
        buf = io.StringIO()
        with redirect_stdout(buf):
            rc = run_orient(argparse.Namespace(command="orient", project=str(self.project), short=True))
        self.assertEqual(rc, 0)
        out = buf.getvalue()
        self.assertIn("## CURRENT RUNTIME STATE", out)
        self.assertIn("Next session: SESSION_002", out)


class TestStartCodex(TruthStateTestCase):
    def test_codex_command_parses_short_flag(self):
        args = build_parser().parse_args(["codex", "--mode=execute", "--short"])
        self.assertEqual(args.command, "codex")
        self.assertEqual(args.mode, "execute")
        self.assertTrue(args.short)

    def test_codex_command_falls_back_helpfully_when_binary_is_missing(self):
        (self.project / "README.md").write_text("# Demo\n", encoding="utf-8")
        (self.project / "CLAUDE.md").write_text("# Claude\n", encoding="utf-8")
        buf = io.StringIO()
        with patch("cli.start_codex.shutil.which", return_value=None):
            with redirect_stdout(buf):
                rc = run_codex(
                    argparse.Namespace(
                        command="codex",
                        project=str(self.project),
                        user=None,
                        mode="execute",
                        model=None,
                        short=True,
                    )
                )
        self.assertEqual(rc, 0)
        out = buf.getvalue()
        self.assertIn("Codex CLI: not found on PATH.", out)
        self.assertIn("Verification config: created `.context-kit/verify.yaml`.", out)
        self.assertIn("Clipboard unavailable.", out)
        self.assertIn("Paste the prompt below into Codex.", out)
        self.assertIn("Essential rules:", out)
        self.assertIn("context-kit inspect", out)
        self.assertIn("context-kit verify", out)

    def test_codex_command_preserves_existing_verify_config(self):
        verify = self.project / ".context-kit" / "verify.yaml"
        verify.parent.mkdir(parents=True, exist_ok=True)
        verify.write_text("sentinel: keep\n", encoding="utf-8")
        buf = io.StringIO()
        with patch("cli.start_codex.shutil.which", return_value=None):
            with redirect_stdout(buf):
                rc = run_codex(
                    argparse.Namespace(
                        command="codex",
                        project=str(self.project),
                        user=None,
                        mode="execute",
                        model=None,
                        short=True,
                    )
                )
        self.assertEqual(rc, 0)
        self.assertEqual(verify.read_text(encoding="utf-8"), "sentinel: keep\n")
        self.assertIn("already exists", buf.getvalue())

    def test_start_codex_creates_verify_config_when_missing(self):
        (self.project / "README.md").write_text("# Demo\n", encoding="utf-8")
        (self.project / "CLAUDE.md").write_text("# Claude\n", encoding="utf-8")
        (self.project / "docs" / "CONTEXT_KIT_WHAT_IT_IS.md").write_text("# What it is\n", encoding="utf-8")
        buf = io.StringIO()
        with redirect_stdout(buf):
            rc = run_start_codex(
                argparse.Namespace(command="start-codex", project=str(self.project), user=None)
            )
        self.assertEqual(rc, 0)
        verify = self.project / ".context-kit" / "verify.yaml"
        self.assertTrue(verify.exists())
        text = verify.read_text(encoding="utf-8")
        self.assertIn("canonical_docs:", text)
        self.assertIn("00-START-NEXT-SESSION.md", text)
        self.assertIn("README.md", text)
        self.assertIn("CLAUDE.md", text)
        self.assertIn("docs/CONTEXT_KIT_INVENTORY.md", text)
        self.assertIn("docs/CONTEXT_KIT_WHAT_IT_IS.md", text)
        self.assertNotIn("docs/PLATFORM_INVENTORY.md", text)
        self.assertNotIn("docs/PLATFORM_WHAT_IT_IS.md", text)
        self.assertIn("Verification config: created", buf.getvalue())

    def test_start_codex_preserves_existing_verify_config(self):
        verify = self.project / ".context-kit" / "verify.yaml"
        verify.parent.mkdir(parents=True, exist_ok=True)
        verify.write_text("sentinel: keep\n", encoding="utf-8")
        buf = io.StringIO()
        with redirect_stdout(buf):
            rc = run_start_codex(
                argparse.Namespace(command="start-codex", project=str(self.project), user=None)
            )
        self.assertEqual(rc, 0)
        self.assertEqual(verify.read_text(encoding="utf-8"), "sentinel: keep\n")
        self.assertIn("already exists", buf.getvalue())

    def test_startup_prompt_mentions_verify_and_historical_policy(self):
        out = render_codex_prompt(self.project)
        self.assertIn("context-kit inspect", out)
        self.assertIn("context-kit verify", out)
        self.assertIn(".context-kit/verify.yaml", out)
        self.assertIn("historical docs as memory", out)
        self.assertIn("runtime and config files as truth", out)

    def test_generates_startup_prompt(self):
        out = render_codex_prompt(self.project)
        self.assertIn("## CONTEXT-KIT SESSION START", out)
        self.assertIn("Project: demo", out)
        self.assertIn("Version: 0.15.0", out)
        self.assertIn("Tests: 1 discovered", out)
        self.assertNotIn("Tests: 1 passing", out)
        self.assertIn("Latest handoff: SESSION_001", out)
        self.assertIn("Implement the next thing.", out)
        self.assertIn("## TRUST / VERIFY / IGNORE", out)
        self.assertIn("Warnings are advisory; only blocking items stop work.", out)
        self.assertNotIn("## EXECUTION MODE", out)
        self.assertNotIn("Model hint:", out)

    def test_default_mode_is_design_prompt(self):
        out = render_codex_prompt(self.project, mode="design")
        self.assertIn("Build understanding", out)
        self.assertNotIn("You are executing a defined task.", out)

    def test_execute_mode_adds_minimal_execution_rules(self):
        out = render_codex_prompt(self.project, mode="execute")
        self.assertIn("## EXECUTION MODE", out)
        self.assertIn("You are executing a defined task.", out)
        self.assertIn("- Do not redesign systems", out)
        self.assertIn("- Apply minimal changes only", out)
        self.assertIn("ask before acting", out)

    def test_model_hint_inclusion(self):
        out = render_codex_prompt(self.project, model="cheap")
        self.assertIn("Model hint: use a lower-cost / faster model for this task.", out)
        self.assertNotIn("## EXECUTION MODE", out)

    def test_short_prompt_is_compact(self):
        out = render_codex_prompt(self.project, short=True)
        self.assertIn("Project: demo", out)
        self.assertIn("Tests: 1 discovered", out)
        self.assertIn("Latest handoff: SESSION_001", out)
        self.assertIn("Next task:", out)
        self.assertIn("Implement the next thing.", out)
        self.assertIn("Essential rules:", out)
        self.assertNotIn("## TRUST / VERIFY / IGNORE", out)
        self.assertNotIn("Key docs:", out)
        self.assertNotIn("Constraints:", out)
        self.assertNotIn("Tests: 1 passing", out)

    def test_execute_short_prompt_includes_execution_rules(self):
        out = render_codex_prompt(self.project, mode="execute", short=True)
        self.assertIn("## EXECUTION MODE", out)
        self.assertIn("- Do not redesign systems", out)
        self.assertIn("Essential rules:", out)

    def test_model_hint_short_prompt(self):
        out = render_codex_prompt(self.project, model="cheap", short=True)
        self.assertIn("Model hint: use a lower-cost / faster model for this task.", out)
        self.assertNotIn("## EXECUTION MODE", out)

    def test_cli_entrypoint_prints_prompt(self):
        buf = io.StringIO()
        with redirect_stdout(buf):
            rc = run_start_codex(
                argparse.Namespace(command="start-codex", project=str(self.project), user=None, short=False)
            )
        self.assertEqual(rc, 0)
        out = buf.getvalue()
        self.assertIn("Steps:", out)
        self.assertIn("## TRUST / VERIFY / IGNORE", out)

    def test_cli_entrypoint_supports_short_flag(self):
        buf = io.StringIO()
        with redirect_stdout(buf):
            rc = run_start_codex(
                argparse.Namespace(command="start-codex", project=str(self.project), user=None, short=True)
            )
        self.assertEqual(rc, 0)
        out = buf.getvalue()
        self.assertIn("Essential rules:", out)
        self.assertNotIn("Key docs:", out)
        self.assertNotIn("## TRUST / VERIFY / IGNORE", out)
        self.assertIn("context-kit inspect", out)
        self.assertIn("context-kit verify", out)

    def test_persona_mode_uses_translation_layer_when_present(self):
        (self.project / "docs" / "DEMO_TRANSLATION_LAYER.md").write_text(
            """# Translation

## Personas / Audiences

| Person | Cares about |
|---|---|
| test | concise QA framing |
""",
            encoding="utf-8",
        )
        out = render_codex_prompt(self.project, user="test")
        self.assertIn("Persona mode:", out)
        self.assertIn("Matched persona:", out)
        self.assertIn("Do not change facts", out)


if __name__ == "__main__":
    unittest.main()
