"""context-kit `exec` subcommand: render an execution-ready AI prompt.

Reads the same audit workspace as ``context-kit fix``
(``docs/audit/AUDIT_V1.md`` + ``docs/audit/CLEANUP_PLAN.md``) and
emits a structured prompt an agent can execute against. Where ``fix``
prints a human-readable outline, ``exec`` produces a longer, fully-
framed prompt with Goal / Context / Instructions / Phase tasks /
Constraints / Output expectations sections.

Read-only by contract: never modifies files, never invokes an AI,
never executes any of the steps it prints. ``--phase N`` and
``--next`` mirror the ``fix`` command's filtering options and remain
mutually exclusive.

Validation reuses ``cli.fix._workspace_ready`` and
``cli.fix._parse_phases`` so the two commands speak the same
markdown grammar — adding new phase shapes only needs to land in
fix.py.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from cli.fix import (
    Phase,
    _AUDIT_DIR,
    _AUDIT_V1,
    _CLEANUP_PLAN,
    _NOT_INITIALIZED,
    _parse_phases,
    _workspace_ready,
)


_PROMPT_INSTRUCTIONS = """\
Instructions:
1. Treat each task as a discrete change. Prefer one commit per task
   unless the plan groups tasks under a phase that should land
   together.
2. Run the project's existing test suite once to establish a
   baseline before starting.
3. After every task, re-run the test suite. If anything regresses,
   stop and report — do not stack additional tasks on top of a
   broken state.
4. Tasks that name shell commands or file paths verbatim should be
   followed literally unless the project's conventions require a
   different invocation (e.g. `pnpm` instead of `npm`).
5. If a task's intent is ambiguous, re-read `docs/audit/AUDIT_V1.md`
   for the original finding before guessing."""


_PROMPT_CONSTRAINTS = """\
Constraints:
- Do not modify source files outside the scope of the listed tasks.
  Audit-driven cleanup is intentionally narrow.
- Do not invent new tasks. If a finding seems important but is not
  in the plan, append it to a follow-ups doc (e.g.
  `docs/cleanup/FOLLOWUPS.md`) — do not silently expand scope.
- Do not commit on a broken test suite. Push back on the user
  before bypassing.
- Read-only operations (regen commands, verifiers) should run first
  inside each phase whenever possible — they reveal current truth
  before any mutation."""


_PROMPT_OUTPUT_EXPECTATIONS = """\
Output expectations:
Report back as if you're updating a small project team — concise,
specific, action-oriented. For each task you complete:
  1. Which task (phase number + first ~10 words of the bullet)
  2. Files changed (paths)
  3. Test result before / after
  4. Anything you didn't do, and why

When the requested scope finishes, summarize in one paragraph:
what landed, what's still open, and what you need from the team
next."""


_PROMPT_OUTPUT_EXPECTATIONS_SINGLE_STEP = """\
Output expectations:
Report back as if you're updating a small project team — concise,
specific, action-oriented. This invocation requested a single step:
  1. The task you executed (verbatim, from "Task" above)
  2. Files changed (paths)
  3. Test result before / after
  4. Whether the project is ready for the next
     `context-kit exec --next` invocation, or whether something
     blocks it. If you need anything from the team to unblock,
     name it explicitly."""


def run_exec(args: argparse.Namespace) -> int:
    audit_dir = Path.cwd() / _AUDIT_DIR
    v1 = audit_dir / _AUDIT_V1
    plan = audit_dir / _CLEANUP_PLAN

    if not _workspace_ready(v1, plan):
        print(_NOT_INITIALIZED)
        return 1

    phases = _parse_phases(plan.read_text(encoding="utf-8"))
    if not phases:
        print(
            "context-kit: no phases parsed from "
            f"{(_AUDIT_DIR / _CLEANUP_PLAN).as_posix()}. Expected `### Phase N` headings "
            "or `- Phase N` bullets."
        )
        return 1

    if getattr(args, "next_step", False):
        return _print_next_prompt(phases)
    if getattr(args, "phase", None) is not None:
        return _print_phase_prompt(phases, args.phase)
    return _print_full_prompt(phases)


# ---------------------------------------------------------------------------
# Prompt rendering
# ---------------------------------------------------------------------------


def _format_phase_block(phase: Phase) -> str:
    header = f"Phase {phase.number}"
    if phase.title:
        header += f" — {phase.title}"
    lines = [header]
    for step in phase.steps:
        lines.append(f"- {step}")
    return "\n".join(lines)


def _format_all_phases(phases: list[Phase]) -> str:
    return "\n\n".join(_format_phase_block(p) for p in phases)


def _build_prompt(*, goal: str, tasks_block: str, output_expectations: str) -> str:
    return "\n\n".join(
        [
            "=== CONTEXT-KIT EXEC PROMPT ===",
            f"Goal:\n{goal}",
            (
                "Context:\n"
                "This prompt was generated by `context-kit exec` from a project "
                "that has run `context-kit audit` and filled\n"
                f"`{(_AUDIT_DIR / _AUDIT_V1).as_posix()}` and `{(_AUDIT_DIR / _CLEANUP_PLAN).as_posix()}`. "
                "The Phase tasks below were parsed verbatim from\n"
                f"`{(_AUDIT_DIR / _CLEANUP_PLAN).as_posix()}`. The audit findings that "
                "motivated each task live in\n"
                f"`{(_AUDIT_DIR / _AUDIT_V1).as_posix()}` — read them when a task's rationale "
                "is unclear."
            ),
            _PROMPT_INSTRUCTIONS,
            f"Phase tasks:\n{tasks_block}",
            _PROMPT_CONSTRAINTS,
            output_expectations,
        ]
    )


def _print_full_prompt(phases: list[Phase]) -> int:
    goal = (
        "Execute the phased cleanup plan in full, one phase at a time, "
        "in numeric order. Verify the project's tests / build remain "
        "green after each phase before starting the next."
    )
    print(
        _build_prompt(
            goal=goal,
            tasks_block=_format_all_phases(phases),
            output_expectations=_PROMPT_OUTPUT_EXPECTATIONS,
        )
    )
    return 0


def _print_phase_prompt(phases: list[Phase], number: int) -> int:
    target = next((p for p in phases if p.number == number), None)
    if target is None:
        available = ", ".join(str(p.number) for p in phases)
        print(f"context-kit: phase {number} not found (available: {available}).")
        return 1
    goal = (
        f"Execute Phase {number} of the cleanup plan only. Do not start "
        "other phases in the same invocation. Verify tests / build remain "
        "green when finished."
    )
    print(
        _build_prompt(
            goal=goal,
            tasks_block=_format_phase_block(target),
            output_expectations=_PROMPT_OUTPUT_EXPECTATIONS,
        )
    )
    return 0


def _print_next_prompt(phases: list[Phase]) -> int:
    for phase in phases:
        if phase.steps:
            first_step = phase.steps[0]
            goal = (
                f"Execute exactly one task from Phase {phase.number}: the "
                "first bullet listed under Task below. Stop after this single "
                "task — do not continue into the rest of the phase."
            )
            tasks_block = (
                f"Phase {phase.number}"
                + (f" — {phase.title}" if phase.title else "")
                + f"\nTask: {first_step}"
            )
            print(
                _build_prompt(
                    goal=goal,
                    tasks_block=tasks_block,
                    output_expectations=_PROMPT_OUTPUT_EXPECTATIONS_SINGLE_STEP,
                )
            )
            return 0
    print("context-kit: no steps found in any phase.")
    return 1
