"""context-kit `inventory` subcommand: runtime-derived inventory generator.

Three modes:

* ``--write``  — update the managed block inside ``docs/CONTEXT_KIT_INVENTORY.md``.
* ``--check``  — exit 0 only if the managed block is current; 1 if stale.
* ``--json``   — print machine-readable JSON to stdout. Read-only.

The managed block lives between two HTML-comment markers:

    <!-- context-kit:inventory:start -->
    ... auto-generated content ...
    <!-- context-kit:inventory:end -->

Everything outside those markers is human-written and preserved on every
``--write``. The generator writes nothing else to the inventory file.

This command runs in the same process as the rest of the CLI, so subcommand
introspection trusts ``context_kit.build_parser()`` directly. Generated
projects ship a byte-identical entry point, so the assumption holds end-to-end.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

START_MARKER = "<!-- context-kit:inventory:start -->"
END_MARKER = "<!-- context-kit:inventory:end -->"

DEFAULT_INVENTORY_REL = Path("docs/CONTEXT_KIT_INVENTORY.md")
SCHEMA_VERSION = 1

# When --check compares blocks, the "Last generated:" line is normalized
# on both sides so a fresh timestamp doesn't count as drift.
_TIMESTAMP_LINE_RE = re.compile(r"<!-- Last generated:[^>]*-->")
_TIMESTAMP_PLACEHOLDER = "<!-- Last generated: NORMALIZED -->"

# Default header used when the inventory file does not yet exist. Kept
# minimal so the human owner of the file can replace it freely — only
# the markers are load-bearing.
_DEFAULT_HEADER = """---
title: "Repo Inventory (auto-generated)"
status: auto
---

# Repo Inventory

This file is partly auto-generated. Everything between the
`context-kit:inventory:start` / `end` markers below is regenerated by
`context-kit inventory --write`. Edit anywhere outside the markers
freely; the generator will not touch it.

"""

# Comment shown when we have to add the markers to a pre-existing file
# that was hand-written. Documents what just changed.
_APPEND_INTRO = (
    "\n\n<!-- The block below was added by `context-kit inventory --write`. -->\n"
    "<!-- It will be regenerated on every `--write`. Edit outside the markers freely. -->\n\n"
)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def run_inventory(args: argparse.Namespace) -> int:
    project = Path(args.project).resolve() if args.project else Path.cwd().resolve()

    if not project.is_dir():
        print(f"context-kit: {project} is not a directory.")
        return 2

    if args.json:
        inventory = collect_inventory(project)
        print(json.dumps(inventory, indent=2, sort_keys=True))
        return 0

    if args.check:
        is_current, reason = check_inventory(project)
        print(f"context-kit: {reason}")
        return 0 if is_current else 1

    if args.write:
        path, action = write_inventory(project)
        try:
            rel = path.relative_to(project)
        except ValueError:
            rel = path
        print(f"context-kit: {action} {rel}")
        return 0

    print(
        "context-kit inventory: pass exactly one of --write, --check, or --json.\n"
        "Run `context-kit inventory --help` for details."
    )
    return 2


# ---------------------------------------------------------------------------
# Data collection
# ---------------------------------------------------------------------------


def collect_inventory(project: Path) -> dict:
    """Return the runtime-derived inventory facts as a plain dict."""
    return {
        "schema_version": SCHEMA_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "project_path": str(project),
        "package": _package_metadata(project),
        "cli_subcommands": _cli_subcommands(),
        "cli_modules": _cli_modules(project),
        "guide_docs": _guide_docs(project),
        "docs_files": _docs_files(project),
        "handoff_files": _handoff_files(project),
        "template_files": _template_files(project),
        "starter_files": _starter_files(project),
        "scaffold_files": _scaffold_files(project),
        "test_files": _test_files(project),
        "test_count": _test_count(project),
        "skill_files": _skill_files(project),
        "tracked_file_count": _tracked_file_count(project),
        "hotpath": _hotpath_summary(project),
    }


def _cli_subcommands() -> list[str]:
    """Trust ``context_kit.build_parser()`` from this process.

    The entry script ships byte-identical to every generated project via
    RUNTIME_COPY, so the in-process parser is the same parser the user
    invokes from their project root. No project arg needed.
    """
    try:
        from context_kit import build_parser  # type: ignore
    except ImportError:
        return []
    parser = build_parser()
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return sorted(action.choices.keys())
    return []


def _cli_modules(project: Path) -> list[str]:
    cli = project / "cli"
    if not cli.is_dir():
        return []
    return sorted(p.name for p in cli.glob("*.py") if p.is_file())


def _guide_docs(project: Path) -> list[str]:
    """Locate the 8 numbered guide docs.

    In the source repo they live at ``cli/_pattern/`` (so they ship as
    package data inside a wheel). In a generated project they live at
    ``docs/docs-pattern/`` (the materialized copy). Check both, dedupe
    by name. Returns empty list if neither location has them.
    """
    candidates: dict[str, None] = {}
    for base in (
        project / "cli" / "_pattern",
        project / "docs" / "docs-pattern",
        project,  # legacy: pre-PyPI source-repo root layout
    ):
        if not base.is_dir():
            continue
        for p in base.glob("0[1-8]_*.md"):
            if p.is_file():
                candidates[p.name] = None
    return sorted(candidates.keys())


def _docs_files(project: Path) -> list[str]:
    """Top-level files in ``docs/``, excluding the handoffs subdirectory.

    Excludes the inventory file itself for the same self-reference
    reason ``_hotpath_summary`` does — including it would shift the
    count between ``--write`` and the next ``--check``.
    """
    docs = project / "docs"
    if not docs.is_dir():
        return []
    inv_name = DEFAULT_INVENTORY_REL.name
    return sorted(
        p.name for p in docs.glob("*.md")
        if p.is_file() and p.name != inv_name
    )


def _handoff_files(project: Path) -> list[str]:
    handoffs = project / "docs" / "handoffs"
    if not handoffs.is_dir():
        return []
    return sorted(p.name for p in handoffs.glob("*.md") if p.is_file())


def _template_files(project: Path) -> list[str]:
    templates = project / "templates"
    if not templates.is_dir():
        return []
    return sorted(p.name for p in templates.iterdir() if p.is_file())


def _starter_files(project: Path) -> list[str]:
    """Files under ``starter/``, excluding the optional ``scaffold/`` subtree."""
    starter = project / "starter"
    if not starter.is_dir():
        return []
    out: list[str] = []
    for p in starter.rglob("*"):
        if not p.is_file():
            continue
        rel = p.relative_to(starter)
        if rel.parts and rel.parts[0] == "scaffold":
            continue
        out.append(str(rel))
    return sorted(out)


def _scaffold_files(project: Path) -> list[str]:
    scaffold = project / "starter" / "scaffold"
    if not scaffold.is_dir():
        return []
    return sorted(
        str(p.relative_to(scaffold))
        for p in scaffold.rglob("*")
        if p.is_file()
    )


def _test_files(project: Path) -> list[str]:
    tests = project / "tests"
    if not tests.is_dir():
        return []
    return sorted(p.name for p in tests.glob("test_*.py") if p.is_file())


def _test_count(project: Path) -> int:
    """Count ``def test_*(`` definitions across ``tests/test_*.py``.

    Cheap, deterministic, and matches what unittest discovery would find
    for the conventional test-method pattern. Skips parametrized
    multipliers — fine for our use case (and any real test count drift is
    surfaced by running the suite).
    """
    tests = project / "tests"
    if not tests.is_dir():
        return 0
    pattern = re.compile(r"^\s*def\s+test_\w+\s*\(", re.MULTILINE)
    count = 0
    for path in tests.glob("test_*.py"):
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        count += len(pattern.findall(text))
    return count


def _skill_files(project: Path) -> list[str]:
    """Every ``SKILL.md`` discovered under any known skill location.

    Source repo (post-PyPI):    ``cli/_skills/<name>/SKILL.md``
    Generated project:          ``.claude/skills/<name>/SKILL.md``
    Source repo (legacy):       ``skills/<name>/SKILL.md``

    Returns paths relative to the project root, deduped.
    """
    found: dict[str, None] = {}
    for base_rel in ("cli/_skills", ".claude/skills", "skills"):
        base = project / base_rel
        if not base.is_dir():
            continue
        for p in base.rglob("SKILL.md"):
            if p.is_file():
                try:
                    rel = str(p.relative_to(project))
                except ValueError:
                    rel = str(p)
                found[rel] = None
    return sorted(found.keys())


def _tracked_file_count(project: Path) -> int | None:
    """Returns ``None`` when not in a git repo or git is unavailable."""
    if not (project / ".git").exists():
        return None
    try:
        result = subprocess.run(
            ["git", "-C", str(project), "ls-files"],
            capture_output=True,
            check=False,
            text=True,
        )
    except (OSError, FileNotFoundError):
        return None
    if result.returncode != 0:
        return None
    return sum(1 for line in result.stdout.splitlines() if line)


def _package_metadata(project: Path) -> dict:
    """Extract a small, well-defined slice of pyproject.toml.

    Uses regex rather than ``tomllib`` (which is 3.11+) to keep
    context-kit's zero-dep promise on Python 3.9/3.10.
    """
    pyproject = project / "pyproject.toml"
    if not pyproject.is_file():
        return {}
    try:
        text = pyproject.read_text(encoding="utf-8")
    except OSError:
        return {}
    fields: dict[str, str] = {}
    for key in ("name", "version", "description", "requires-python"):
        m = re.search(
            rf'^\s*{re.escape(key)}\s*=\s*"([^"]*)"',
            text,
            re.MULTILINE,
        )
        if m:
            fields[key.replace("-", "_")] = m.group(1)
    return fields


def _hotpath_summary(project: Path) -> dict:
    """Reuse ``cli.hotpath`` collection logic in-process. Empty dict on failure.

    The inventory file itself is excluded — this summary lives inside
    that file, so including it would make the summary change every
    time it is regenerated and break ``--check`` immediately after
    ``--write``. Self-reference is the bug, exclusion is the fix.
    """
    try:
        from .hotpath import _collect_files, _with_sizes  # type: ignore
    except ImportError:
        return {}
    try:
        files, source = _collect_files(project)
        sized = _with_sizes(files)
    except Exception:
        return {}
    inv_path = (project / DEFAULT_INVENTORY_REL).resolve()
    sized = [(p, s) for p, s in sized if p.resolve() != inv_path]
    sized.sort(key=lambda fs: fs[1], reverse=True)
    top = sized[:10]
    top_sum = sum(s for _, s in top)
    total_sum = sum(s for _, s in sized)
    return {
        "source": source,
        "files_scanned": len(sized),
        "top_count": len(top),
        "top_sum_bytes": top_sum,
        "total_bytes": total_sum,
        "top_files": [
            {
                "path": _relpath(p, project),
                "size_bytes": s,
            }
            for p, s in top
        ],
    }


def _relpath(p: Path, project: Path) -> str:
    try:
        return str(p.relative_to(project))
    except ValueError:
        return str(p)


# ---------------------------------------------------------------------------
# Rendering — the markdown that goes between the markers
# ---------------------------------------------------------------------------


def render_block_body(inventory: dict) -> str:
    """Render the markdown body that lives between the start/end markers."""
    pkg = inventory.get("package") or {}
    hp = inventory.get("hotpath") or {}

    lines: list[str] = []
    lines.append(
        "<!-- Auto-generated by `context-kit inventory --write`. Do not edit by hand. -->"
    )
    lines.append(f"<!-- Last generated: {inventory['generated_at']} -->")
    lines.append(f"<!-- Schema version: {inventory['schema_version']} -->")
    lines.append("")
    lines.append("## Auto-generated counts")
    lines.append("")
    lines.append("| Item | Count | Notes |")
    lines.append("|---|---|---|")

    def row(label: str, count, note: str) -> None:
        lines.append(f"| {label} | {count} | {note} |")

    row("CLI subcommands", len(inventory["cli_subcommands"]),
        ", ".join(inventory["cli_subcommands"]) or "—")
    row("Python modules in `cli/`", len(inventory["cli_modules"]),
        ", ".join(inventory["cli_modules"]) or "—")
    row("Top-level guide docs", len(inventory["guide_docs"]),
        "matches `0[1-8]_*.md`")
    row("`docs/` files (top-level)", len(inventory["docs_files"]),
        "excludes handoffs")
    row("Session handoffs", len(inventory["handoff_files"]),
        "`docs/handoffs/`")
    row("Templates", len(inventory["template_files"]), "`templates/`")
    row("Starter files (excl. scaffold)", len(inventory["starter_files"]),
        "`starter/`")
    row("Scaffold files", len(inventory["scaffold_files"]),
        "`starter/scaffold/`")
    row("Test files", len(inventory["test_files"]), "`tests/test_*.py`")
    row("Tests collected", inventory["test_count"],
        "from `def test_` parse")
    row("Skill files", len(inventory["skill_files"]), "`skills/**/SKILL.md`")
    tracked = inventory["tracked_file_count"]
    row("Tracked files",
        "(not a git repo)" if tracked is None else tracked,
        "from `git ls-files`")

    if pkg:
        lines.append("")
        lines.append("## Package metadata (from `pyproject.toml`)")
        lines.append("")
        for key, label in (
            ("name", "name"),
            ("version", "version"),
            ("description", "description"),
            ("requires_python", "requires-python"),
        ):
            if key in pkg:
                lines.append(f"- **{label}:** {pkg[key]}")

    if hp:
        lines.append("")
        lines.append("## Hot-path summary")
        lines.append("")
        lines.append(f"- **Source:** {hp['source']}")
        lines.append(f"- **Files scanned:** {hp['files_scanned']}")
        lines.append(
            f"- **Top {hp['top_count']} sum:** {_fmt_bytes(hp['top_sum_bytes'])}"
        )
        lines.append(f"- **Total size:** {_fmt_bytes(hp['total_bytes'])}")

    return "\n".join(lines)


def _fmt_bytes(n: int) -> str:
    if n < 1024:
        return f"{n} B"
    kb = n / 1024
    if kb < 1024:
        return f"{kb:.1f} KB"
    mb = kb / 1024
    return f"{mb:.2f} MB"


# ---------------------------------------------------------------------------
# File operations — the part that mutates
# ---------------------------------------------------------------------------


def write_inventory(
    project: Path,
    inventory_path: Path | None = None,
) -> tuple[Path, str]:
    """Write or update the managed block. Returns (path, action)."""
    if inventory_path is None:
        inventory_path = project / DEFAULT_INVENTORY_REL

    inventory = collect_inventory(project)
    block_body = render_block_body(inventory)
    new_block = f"{START_MARKER}\n{block_body}\n{END_MARKER}"

    if not inventory_path.exists():
        inventory_path.parent.mkdir(parents=True, exist_ok=True)
        content = _DEFAULT_HEADER + new_block + "\n"
        inventory_path.write_text(content, encoding="utf-8")
        return inventory_path, "created"

    existing = inventory_path.read_text(encoding="utf-8")

    if START_MARKER in existing and END_MARKER in existing:
        new_content = _replace_block(existing, new_block)
        inventory_path.write_text(new_content, encoding="utf-8")
        return inventory_path, "updated"

    sep = "" if existing.endswith("\n") else "\n"
    new_content = existing + sep + _APPEND_INTRO + new_block + "\n"
    inventory_path.write_text(new_content, encoding="utf-8")
    return inventory_path, "appended-block"


def _replace_block(existing: str, new_block: str) -> str:
    pre, _, after_start = existing.partition(START_MARKER)
    _, _, post = after_start.partition(END_MARKER)
    return pre + new_block + post


def check_inventory(
    project: Path,
    inventory_path: Path | None = None,
) -> tuple[bool, str]:
    """Return ``(is_current, reason)``."""
    if inventory_path is None:
        inventory_path = project / DEFAULT_INVENTORY_REL

    if not inventory_path.exists():
        return False, f"inventory file not found: {inventory_path}"

    existing = inventory_path.read_text(encoding="utf-8")
    if START_MARKER not in existing or END_MARKER not in existing:
        return False, "inventory file has no managed block (run --write to add one)"

    inventory = collect_inventory(project)
    new_block_body = render_block_body(inventory)
    new_block = f"{START_MARKER}\n{new_block_body}\n{END_MARKER}"

    start_idx = existing.index(START_MARKER)
    end_idx = existing.index(END_MARKER) + len(END_MARKER)
    existing_block = existing[start_idx:end_idx]

    norm_existing = _TIMESTAMP_LINE_RE.sub(_TIMESTAMP_PLACEHOLDER, existing_block)
    norm_new = _TIMESTAMP_LINE_RE.sub(_TIMESTAMP_PLACEHOLDER, new_block)

    if norm_existing == norm_new:
        return True, "inventory is current"
    return False, "inventory is stale (regenerate with --write)"
